### ISSUE TITLE
Comentarios Backlog

### ISSUE THREAD

**Issue by L2JE** [Juanemauro/MDDS2021Grupo15#1]
>En la entrega van unicamente las user stories (evitar comentarios o cosas que no se correspondan con la estructura de una user story explicada en clase).
>Si pueden entregar en un excel/google sheets, mejor. Los nombres de las US son los que van a aparecer directamente sobre el USmap.
>recordar: NO TIENE QUE FALTAR NINGUN "para" en las US.

#P1
¿Es necesario escribir las opciones en los criterios de aceptaciones?
>Si.

¿Esta user story es válida? Porque en el párrafo 4 dice que el cartonero tiene que marcar los domicilios visitados. ¿Va una o van las dos?
>En ningun lado dice que el ciudadano tenga que notificar.

#P2
¿está bien separarlas así?
>En donde pide que se le envie al cartonero? Recordar que por lo general un cartonero en alguien que no pudo acceder a un trabajo mejor, es decir, es poco probable que pueda acceder a una pagina web...

#P3
 ¿Tenemos que hacer un user story para que se registre? Porque estoy incluiría toda la parte de contraseñas, etc.
>La secretaria unicamente se loguea, es la unica que puede acceder a funcionalidades tan cruciales, por lo que no existe un registro (se hace de forma interna, no nos incumbe).

¿Modificar y eliminar sería lo mismo? Modificar sería cambiar el valor de un dato, eliminar sería borrar el valor del dato y quedaría vacío. ¿Cómo querés que implementemos esto? ¿El objetivo puede repetirse para las tres?
>Modificar es cambiar datos y eliminar es desaparecer todos los datos de un cartonero.

#P4
¿Se auto-registra o lo hace la secretaria en el momento?
>Muy bien! la secretaria es la que accede al sistema, si bien es el cartonero el que usa la funcionalidad, la secretaria debe estar ahi (haria de proxy digamos)

Como cartonero tengo que poder registrar mis datos. ¿Esto sería un criterio de aceptación de 6) o una user story a parte? Si lo vemos como un caso de uso sería un flujo alternativo
>En la narrativa dice que cuando va a entregar, si no esta registrado, este puede hacerlo. Recordar que el cartonero se considera es una persona que no sabe usar al sistema.

#P7
Postulante = el que dice que puede llevar los materiales al centro de acoplo. Solicitante = el que necesita comunicarse con el postulante.
>Recordar usar siempre el lenguaje del cliente (SIEMPRE y mas fuera de la uni), en la narrativa se usan las palabras "Postular" y "Cargar".

¿Cómo se autentica el ciudadano? ¿Tiene que tener una cuenta? En caso de que la necesite, ¿tenemos que hacerlo en una user story a parte
>Es nueva funcionalidad? Entonces si, no lo es? entonces no. En la narrativa no se habla en ningun momento de un login para ciudadanos asi que es valido no hacerlo. Pero si lo hacen deben prestar atencion en como afecta al resto y tener login y registro.

#P8
Como secretaria quiero registrar la cantidad de kilos vendidos para (¿sería el mismo objetivo que 18?).
>No se que es 18 pero aca se pide registrar lo que se vendio por convenio a las recicladoras(cosa externa al sistema).

**Comment by Juanemauro** [comment]
Finalizada.
